### ISSUE TITLE
metadata.json文件中的bounds格式应该为逗号分隔（而不是空格）的坐标

### ISSUE THREAD

**Issue by ten2net** [cugxy/map_download#4]
我使用mbutil把下载的jpg瓦片导入到.mbtile文件，然后用MapTiler打开时报“bounds格式不正确”的错误

**Comment by cugxy** [comment]
我的这个只适用与 cesium 加载地形影像时使用, 可以麻烦给出你所说的 MapTiler 相关资料及其格式要求, 我看有时间做出相应兼容吗?
