### ISSUE TITLE
写入数据库时应该把metadata.json的数据也写入到数据库中的metadata表中，这样可兼容MapTiler等工具打开数据库直接查看地图

### ISSUE THREAD

**Issue by ten2net** [cugxy/map_download#5]
按照Mbtile1.2的规范，应该有两张表（metadata,tiles）.为何只有一个tiles表？

**Comment by cugxy** [comment]
我的这个只适用与 cesium 加载地形影像时使用, 可以麻烦给出你所说的 MapTiler 相关资料及其格式要求, 我看有时间做出相应兼容吗?

**Comment by ten2net** [comment]
这是1.2版的规范：https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md
这是maptiler的网址：https://www.maptiler.com/
使用MapTiler Desktop这个工具可以很方便查看.mbtiles文件。我是先使用它来快速预览生成的地图，满意了再发布供cesium使用。

**Comment by ten2net** [comment]
我试过了，你这个版本的写库的方法里面插入tiles表的tile_row字段的方法有些问题。不能直接插入，应该是y = (2**z - 1) - yy。
```
    def _data2DB(self, x, yy, z, file):
        """
        写入数据库
        :param x:
        :param y:
        :param z:
        :param file:  file path
        :return: 0 no need to write or exists -1 fail 1 success
        """
        y = (2**z - 1) - yy
        ……
```python

**Comment by cugxy** [comment]
好的 谢谢给出的建议, 我会尽快修改
