### ISSUE TITLE
请问如果可以下载成功的话，怎么可以将下载的成果加载到Cesium中呢？ 

### ISSUE THREAD

**Issue by blackcatcjy** [cugxy/map_download#7]
非常感谢！！！我明天下载下来试一下效果。

请问如果可以下载成功的话（我需要下载卫星图和地形图），怎么可以将下载的成果加载到Cesium中呢？

**Comment by blackcatcjy** [comment]
在调用 pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt  失败了。 可能是我太菜了

**Comment by cugxy** [comment]
> 非常感谢！！！我明天下载下来试一下效果。
> 
> 请问如果可以下载成功的话（我需要下载卫星图和地形图），怎么可以将下载的成果加载到Cesium中呢？

请参照cesium 官网 或自己 Google 搜索哦

**Comment by cugxy** [comment]
> 在调用 pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt 失败了。 可能是我太菜了

请自己 Google 一下哦
